---
title: "Assignment"
author: "Alessandro Tenderini"
date: '2022-11-24'
output: html_document
---

```{r}
PATH=getwd()
library(bayestestR)
library(rstanarm)
library(ggplot2)
library(tidyverse)
library(mombf)
library(hdm)
library(glmnet)
library(HDCI)
library(gridExtra)
library(mvtnorm)

```
```{r}
PATH=getwd()

italy <- read_csv(file.path(PATH, "italy_income.csv"), col_names = T)


X <- italy[,-c(1,2,3,4)]
Y <- italy[,3]

data <- cbind(X,Y)

x = model.matrix(Y~., data=data)
y = data$Y
n = nrow(x)
d = ncol(x)

```


```{r}
lasso.bic <- function(y,x,extended=FALSE) {
  #Select model in LASSO path with best BIC (using LASSO regression estimates)
  #Input
  # - y: vector with response variable
  # - x: design matrix
  #
  #Output: list with the following elements
  # - coef: LASSO-estimated regression coefficient with lambda set via BIC
  # - ypred: predicted y
  # - lambda.opt: optimal value of lambda
  # - lambda: data.frame with bic and number of selected variables for each value of lambda
  require(glmnet)
  fit <- glmnet(x=x,y=y,family='gaussian',alpha=1)
  pred <- cbind(1,x) %*% rbind(fit$a0,fit$beta)
  n <- length(y)
  p <- colSums(fit$beta!=0) + 1
  if (!extended){
    bic <- n * log(colSums((y-pred)^2)/length(y)) + n*(log(2*pi)+1) + log(n)*p 
  } else {
    bic <- n * log(colSums((y-pred)^2)/length(y)) + n*(log(2*pi)+1) + log(n)*p + 2*log(choose(ncol(x),p))
  }
  sel <- which.min(bic)
  beta <- c(fit$a0[sel],fit$beta[,sel]); names(beta)[1]= 'Intercept'
  ypred <- pred[,sel]
  ans <- list(coef=beta,ypred=ypred,lambda.opt=fit$lambda[sel],lambda=data.frame(lambda=fit$lambda,bic=bic,nvars=p))
  return(ans)
}
```


```{r}

fit.lassobic = lasso.bic(y,x[,-1]) 
beta.lassobic = fit.lassobic$coef[-1]

length(names(beta.lassobic[which(beta.lassobic!=0)]))
beta.lassobic[which(beta.lassobic!=0)]
```

```{r}
lasso.cv = cv.glmnet(x=x[,-1], y=y, nfolds=10)
beta.lassocv=as.vector(coef(lasso.cv, s='lambda.min'))[-1]
beta.lassocv2=coef(lasso.cv, s='lambda.min')

length(rownames(beta.lassocv2)[-1][which(beta.lassocv!=0)])
rownames(beta.lassocv2)[-1][which(beta.lassocv!=0)]
beta.lassocv[which(beta.lassocv!=0)]
```

```{r}
model <- lm(Y~., data=data)
summary(model)
```
